#!/bin/bash
set -e
if [[ "$(docker images -q picluster/apt-mirror 2> /dev/null)" == "" ]]; then
	./build-image
fi
if [[ "$(docker ps -a --filter="name=picluster-aptmirror" -q 2> /dev/null)" == "" ]]; then
	./start
fi
