#!/bin/bash
docker container stop picluster-aptmirror
docker container rm picluster-aptmirror
docker container run -d -v /storage/aptmirror:/storage/aptmirror --restart unless-stopped --name=picluster-aptmirror -p 9999:9999 picluster/apt-mirror
